<a href="https://colab.research.google.com/github/Abivisu2/Miniprojeto_AbilioAlfredoFrancisco_Analise_de_Dados_T1/blob/main/Miniprojeto_Analise_Varejo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
# Mini-Projeto Avaliativo: Análise de Dados com Python - dados de varejo

import pandas as pd
import numpy as np
from IPython.display import display
# Ler o arquivo usando o separador correto
df = pd.read_csv("Base Varejo.csv", sep=";")

# Verificar a estrutura original
print("Dimensões da base:", df.shape)

print("\nColunas identificadas:")
print(df.columns.tolist())

print("\nInformações da base:")
df.info()

print("\nPrimeiros registos:")
display(df.head())

Dimensões da base: (830000, 14)

Colunas identificadas:
['DATA', 'CO_ID', 'CL_ID', 'CL_GENERO', 'CL_EC', 'CL_FHL', 'CL_SEG', 'PR_ID', 'PR_CAT', 'PR_NOME', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13']

Informações da base:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 830000 entries, 0 to 829999
Data columns (total 14 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   DATA         830000 non-null  object
 1   CO_ID        830000 non-null  int64
 2   CL_ID        830000 non-null  int64
 3   CL_GENERO    830000 non-null  object
 4   CL_EC        830000 non-null  int64
 5   CL_FHL       830000 non-null  int64
 6   CL_SEG       830000 non-null  object
 7   PR_ID        830000 non-null  int64
 8   PR_CAT       830000 non-null  object
 9   PR_NOME      830000 non-null  object
 10  Unnamed: 10  0 non-null       float64
 11  Unnamed: 11  0 non-null       float64
 12  Unnamed: 12  0 non-null       float64
 13  Unnamed: 13  0 non-null       float64
dtypes: float64(4), int64(5), object(5)
memory usage: 88.7+ MB

Primeiros registos:

,DATA,CO_ID,CL_ID,CL_GENERO,CL_EC,CL_FHL,CL_SEG,PR_ID,PR_CAT,PR_NOME,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,01/02/2019,1000,534,M,4,1,C,67,BEBIDAS,REFRIGERANTE GUARANA,NaN,NaN,NaN,NaN
1,01/02/2019,1000,534,M,4,1,C,70,BEBIDAS,REFRIGERANTE OUTROS,NaN,NaN,NaN,NaN
2,01/02/2019,1000,534,M,4,1,C,178,HIGIENE,LENCO UMEDECIDO,NaN,NaN,NaN,NaN
3,01/02/2019,1000,534,M,4,1,C,4,ALIMENTOS,ABACAXI,NaN,NaN,NaN,NaN
4,01/02/2019,1000,534,M,4,1,C,175,LIMPEZA,LIMPADOR MULTIUSO,NaN,NaN,NaN,NaN

In [8]:
#DIAGNÓSTICO E LIMPEZA INICIAL

# Identificar as colunas totalmente vazias
colunas_vazias = df.columns[df.isna().all()].tolist()
print("Colunas totalmente vazias:", colunas_vazias)

# Remover apenas as colunas totalmente vazias
df = df.dropna(axis=1, how="all")
print("\nDimensões após a limpeza:", df.shape)

print("\nColunas restantes:")
print(df.columns.tolist())

df.info()

Colunas totalmente vazias: ['Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13']

Dimensões após a limpeza: (830000, 10)

Colunas restantes:
['DATA', 'CO_ID', 'CL_ID', 'CL_GENERO', 'CL_EC', 'CL_FHL', 'CL_SEG', 'PR_ID', 'PR_CAT', 'PR_NOME']
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 830000 entries, 0 to 829999
Data columns (total 10 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   DATA       830000 non-null  object
 1   CO_ID      830000 non-null  int64
 2   CL_ID      830000 non-null  int64
 3   CL_GENERO  830000 non-null  object
 4   CL_EC      830000 non-null  int64
 5   CL_FHL     830000 non-null  int64
 6   CL_SEG     830000 non-null  object
 7   PR_ID      830000 non-null  int64
 8   PR_CAT     830000 non-null  object
 9   PR_NOME    830000 non-null  object
dtypes: int64(5), object(5)
memory usage: 63.3+ MB

In [9]:
#TRANSFORMAÇÃO E VALIDAÇÃO

# Verificar o formato atual da coluna DATA
print("Tipo original da coluna DATA:", df["DATA"].dtype)
print("\nExemplos de datas:")
print(df["DATA"].head())

# Converter DATA para o formato datetime
df["DATA"] = pd.to_datetime(
    df["DATA"],
    format="%d/%m/%Y",
    errors="coerce"
)

# Verificar se existem datas inválidas
datas_invalidas = df["DATA"].isna().sum()
print("\nDatas inválidas após a conversão:", datas_invalidas)
print("Tipo após a conversão:", df["DATA"].dtype)

# Verificar valores nulos por coluna
print("\nValores nulos por coluna:")
print(df.isna().sum())

# Investigar categorias e nomes de produtos vazios
categorias_vazias = (
    df["PR_CAT"].astype("string").str.strip().eq("").sum()
)

nomes_vazios = (
    df["PR_NOME"].astype("string").str.strip().eq("").sum()
)

print("\nCategorias de produtos vazias:", categorias_vazias)
print("Nomes de produtos vazios:", nomes_vazios)

# Verificar registos totalmente duplicados
duplicados = df.duplicated().sum()
print("\nRegistos totalmente duplicados:", duplicados)

# Confirmar a estrutura atual da base
print("\nDimensões atuais da base:", df.shape)
print("\nTipos de dados atuais:")
print(df.dtypes)

Tipo original da coluna DATA: object

Exemplos de datas:
0    01/02/2019
1    01/02/2019
2    01/02/2019
3    01/02/2019
4    01/02/2019
Name: DATA, dtype: object

Datas inválidas após a conversão: 0
Tipo após a conversão: datetime64[ns]

Valores nulos por coluna:
DATA         0
CO_ID        0
CL_ID        0
CL_GENERO    0
CL_EC        0
CL_FHL       0
CL_SEG       0
PR_ID        0
PR_CAT       0
PR_NOME      0
dtype: int64

Categorias de produtos vazias: 0
Nomes de produtos vazios: 0

Registos totalmente duplicados: 96553

Dimensões atuais da base: (830000, 10)

Tipos de dados atuais:
DATA         datetime64[ns]
CO_ID                 int64
CL_ID                 int64
CL_GENERO            object
CL_EC                 int64
CL_FHL                int64
CL_SEG               object
PR_ID                 int64
PR_CAT               object
PR_NOME              object
dtype: object

In [10]:
#INVESTIGAÇÃO DE DUPLICADOS

# Contar as linhas que fazem parte de duplicações exatas
mascara_duplicados = df.duplicated(keep=False)
linhas_duplicadas = df[mascara_duplicados]

print("Total de linhas envolvidas em duplicações:",
      len(linhas_duplicadas))

print("\nExemplos de registos duplicados:")
display(linhas_duplicadas.head(10))

# Verificar quantas linhas existem por combinação de compra e produto
repeticoes_compra_produto = df.groupby(
    ["CO_ID", "PR_ID"]
).size()

print("\nCombinações compra-produto repetidas:",
      (repeticoes_compra_produto > 1).sum())

print("\nCombinações compra-produto com mais de uma linha:")
display(
    repeticoes_compra_produto[
        repeticoes_compra_produto > 1
    ].head(10)
)

Total de linhas envolvidas em duplicações: 184330

Exemplos de registos duplicados:

,DATA,CO_ID,CL_ID,CL_GENERO,CL_EC,CL_FHL,CL_SEG,PR_ID,PR_CAT,PR_NOME
3,2019-02-01,1000,534,M,4,1,C,4,ALIMENTOS,ABACAXI
7,2019-02-01,1000,534,M,4,1,C,11,ALIMENTOS,AZEITE
14,2019-02-01,1000,534,M,4,1,C,13,ALIMENTOS,BANANA
15,2019-02-01,1000,534,M,4,1,C,218,ALIMENTOS,BIFE DE COXAO MOLE
19,2019-02-01,1000,534,M,4,1,C,13,ALIMENTOS,BANANA
22,2019-02-01,1000,534,M,4,1,C,69,BEBIDAS,REFRIGERANTE LIMaO
34,2019-02-01,1000,534,M,4,1,C,225,ALIMENTOS,ATUM
40,2019-02-01,1000,534,M,4,1,C,4,ALIMENTOS,ABACAXI
46,2019-02-01,1000,534,M,4,1,C,11,ALIMENTOS,AZEITE
49,2019-02-01,1000,534,M,4,1,C,69,BEBIDAS,REFRIGERANTE LIMaO

Combinações compra-produto repetidas: 87777

Combinações compra-produto com mais de uma linha:

CO_ID  PR_ID
1000   4        2
       11       2
       13       2
       69       2
       218      2
       225      2
1078   21       2
       23       2
       25       2
       36       2
dtype: int64

In [11]:
# Validar a consistência dos identificadores de compra

validacao_compras = df.groupby("CO_ID").agg(
    quantidade_clientes=("CL_ID", "nunique"),
    quantidade_datas=("DATA", "nunique"),
    quantidade_linhas=("CO_ID", "size")
)

print("Número de compras distintas:", df["CO_ID"].nunique())

print("Compras associadas a vários clientes:",
      (validacao_compras["quantidade_clientes"] > 1).sum())

print("Compras associadas a várias datas:",
      (validacao_compras["quantidade_datas"] > 1).sum())

print("\nExemplos de compras com vários clientes:")
display(
    validacao_compras[
        validacao_compras["quantidade_clientes"] > 1
    ].head(10)
)

Número de compras distintas: 18471
Compras associadas a vários clientes: 0
Compras associadas a várias datas: 0

Exemplos de compras com vários clientes:

Empty DataFrame
Columns: [quantidade_clientes, quantidade_datas, quantidade_linhas]
Index: []

In [12]:
#TRATAMENTO DE DUPLICADOS EXATOS

# Guardar uma cópia antes da remoção, para podermos comparar
df_antes_deduplicacao = df.copy()

# Contar duplicados exatos antes do tratamento
duplicados_antes = df.duplicated().sum()

# Remover duplicados exatos, mantendo a primeira ocorrência
df = df.drop_duplicates().copy()

# Verificar o resultado
duplicados_depois = df.duplicated().sum()

print("=== RESULTADO DA LIMPEZA ===")
print("Registos antes:", len(df_antes_deduplicacao))
print("Duplicados exatos identificados:", duplicados_antes)
print("Registos removidos:", len(df_antes_deduplicacao) - len(df))
print("Registos após a limpeza:", len(df))
print("Duplicados restantes:", duplicados_depois)
print("Dimensões finais desta etapa:", df.shape)

=== RESULTADO DA LIMPEZA ===
Registos antes: 830000
Duplicados exatos identificados: 96553
Registos removidos: 96553
Registos após a limpeza: 733447
Duplicados restantes: 0
Dimensões finais desta etapa: (733447, 10)

In [13]:
# NORMALIZAÇÃO DOS CAMPOS DE TEXTO

colunas_texto = ["CL_GENERO", "CL_SEG", "PR_CAT", "PR_NOME"]

for coluna in colunas_texto:
    # Converter para texto, remover espaços externos,
    # reduzir espaços consecutivos e padronizar maiúsculas
    df[coluna] = (
        df[coluna]
        .astype("string")
        .str.replace(r"\s+", " ", regex=True)
        .str.strip()
        .str.upper()
    )

print("Campos de texto normalizados.")

print("\nExemplos após a normalização:")
display(df[colunas_texto].head())

print("\nValores nulos após a normalização:")
print(df[colunas_texto].isna().sum())

Campos de texto normalizados.

Exemplos após a normalização:

  CL_GENERO CL_SEG     PR_CAT               PR_NOME
0         M      C    BEBIDAS  REFRIGERANTE GUARANA
1         M      C    BEBIDAS   REFRIGERANTE OUTROS
2         M      C    HIGIENE       LENCO UMEDECIDO
3         M      C  ALIMENTOS               ABACAXI
4         M      C    LIMPEZA     LIMPADOR MULTIUSO

Valores nulos após a normalização:
CL_GENERO    0
CL_SEG       0
PR_CAT       0
PR_NOME      0
dtype: int64

In [14]:
# REGRAS DE VALIDAÇÃO

# Verificar identificadores ausentes
colunas_id = ["CO_ID", "CL_ID", "PR_ID"]

print("Identificadores nulos:")
print(df[colunas_id].isna().sum())

# Verificar compras associadas a mais de um cliente
clientes_por_compra = df.groupby("CO_ID")["CL_ID"].nunique()
compras_multiplos_clientes = (clientes_por_compra > 1).sum()

# Verificar compras associadas a mais de uma data
datas_por_compra = df.groupby("CO_ID")["DATA"].nunique()
compras_multiplas_datas = (datas_por_compra > 1).sum()

# Verificar validade dos campos numéricos
print("\nValores distintos de CL_GENERO:")
print(df["CL_GENERO"].value_counts(dropna=False))

print("\nValores distintos de CL_EC:")
print(df["CL_EC"].value_counts(dropna=False).sort_index())

print("\nValores distintos de CL_FHL:")
print(df["CL_FHL"].value_counts(dropna=False).sort_index())

print("\nRESULTADOS DAS REGRAS DE VALIDAÇÃO")
print(
    "Compras associadas a mais de um cliente:",
    compras_multiplos_clientes
)
print(
    "Compras associadas a mais de uma data:",
    compras_multiplas_datas
)
print(
    "Datas inválidas ou ausentes:",
    df["DATA"].isna().sum()
)

# Validar se o número de filhos está dentro do intervalo observado
filhos_invalidos = (
    df["CL_FHL"].isna()
    | ~df["CL_FHL"].between(0, 4)
)

print(
    "Registros com CL_FHL ausente ou fora do intervalo de 0 a 4:",
    filhos_invalidos.sum()
)

Identificadores nulos:
CO_ID    0
CL_ID    0
PR_ID    0
dtype: int64

Valores distintos de CL_GENERO:
CL_GENERO
F    382427
M    351020
Name: count, dtype: Int64

Valores distintos de CL_EC:
CL_EC
1    172010
2    172283
3    189048
4    179206
5     20900
Name: count, dtype: int64

Valores distintos de CL_FHL:
CL_FHL
0    384986
1     90845
2     94168
3     92407
4     71041
Name: count, dtype: int64

RESULTADOS DAS REGRAS DE VALIDAÇÃO
Compras associadas a mais de um cliente: 0
Compras associadas a mais de uma data: 0
Datas inválidas ou ausentes: 0
Registros com CL_FHL ausente ou fora do intervalo de 0 a 4: 0

In [15]:
# ESTATÍSTICA DESCRITIVA DE CL_FHL


filhos = df["CL_FHL"].dropna()

estatisticas_filhos = pd.Series({
    "Quantidade de registros válidos": filhos.count(),
    "Média": filhos.mean(),
    "Mediana": filhos.median(),
    "Desvio-padrão": filhos.std(),
    "Moda": filhos.mode().iloc[0] if not filhos.mode().empty else np.nan,
    "Valor mínimo": filhos.min(),
    "Primeiro quartil (25%)": filhos.quantile(0.25),
    "Segundo quartil (50%)": filhos.quantile(0.50),
    "Terceiro quartil (75%)": filhos.quantile(0.75),
    "Valor máximo": filhos.max()
})

print("ESTATÍSTICA DESCRITIVA — NÚMERO DE FILHOS")
display(estatisticas_filhos.to_frame(name="Valor").round(2))

print("\nDistribuição do número de filhos:")
display(
    df["CL_FHL"]
    .value_counts(dropna=False)
    .sort_index()
    .rename_axis("Número de filhos")
    .to_frame(name="Quantidade de registros")
)

ESTATÍSTICA DESCRITIVA — NÚMERO DE FILHOS

                                     Valor
Quantidade de registros válidos  733447.00
Média                                 1.15
Mediana                               0.00
Desvio-padrão                         1.42
Moda                                  0.00
Valor mínimo                          0.00
Primeiro quartil (25%)                0.00
Segundo quartil (50%)                 0.00
Terceiro quartil (75%)                2.00
Valor máximo                          4.00

Distribuição do número de filhos:

                  Quantidade de registros
Número de filhos
0                                  384986
1                                   90845
2                                   94168
3                                   92407
4                                   71041

In [16]:
# COMPRAS POR GÊNERO

compras_por_genero = (
    df.groupby("CL_GENERO")
    .agg(
        registros=("CO_ID", "size"),
        compras_distintas=("CO_ID", "nunique"),
        clientes_distintos=("CL_ID", "nunique")
    )
    .sort_values("compras_distintas", ascending=False)
)

print("ANÁLISE POR GÊNERO")
display(compras_por_genero)

ANÁLISE POR GÊNERO

           registros  compras_distintas  clientes_distintos
CL_GENERO
F             382427               9615                 519
M             351020               8856                 481

In [17]:
# DISTRIBUIÇÃO POR CATEGORIA

produtos_por_categoria = (
    df.groupby("PR_CAT")
    .agg(
        registros_de_produtos=("PR_ID", "size"),
        produtos_distintos=("PR_ID", "nunique"),
        compras_com_categoria=("CO_ID", "nunique")
    )
    .sort_values("registros_de_produtos", ascending=False)
)

print("ANÁLISE POR CATEGORIA")
display(produtos_por_categoria)

ANÁLISE POR CATEGORIA

            registros_de_produtos  produtos_distintos  compras_com_categoria
PR_CAT
ALIMENTOS                  384197                 120                  18267
HIGIENE                    137702                  43                  17610
LIMPEZA                    128632                  40                  17475
BEBIDAS                     38264                  12                  14735
PET                         28553                   9                  13495
ACESSORIOS                  12871                   4                   9224
#N/D                         3228                   1                   3228

In [18]:
# TABELA DINÂMICA: GÊNERO × SEGMENTO

tabela_genero_segmento = pd.pivot_table(
    df,
    index="CL_GENERO",
    columns="CL_SEG",
    values="CO_ID",
    aggfunc="nunique",
    fill_value=0
)

print("COMPRAS DISTINTAS POR GÊNERO E SEGMENTO")
display(tabela_genero_segmento)

COMPRAS DISTINTAS POR GÊNERO E SEGMENTO

CL_SEG       A     B     C
CL_GENERO
F          700  5946  2969
M          792  5897  2167